# 1. Application settings
server:
  port: 12345
  servlet:
    session:
      timeout: 1800s
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: pollra-server
  thymeleaf:
    mode: HTML
    cache: false

  # 2. Database settings
  ## 2.1 Redis setting
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session
  redis:
    host: localhost
    port: 6379
    database: 0

  ## 2.2 Postgres + Hikari
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/leatherwaltz
    username: pollra
    password: qwer1234
    maximumPoolSize: 10
    auto-commit: true
